library(gdata);library(WriteXLS);library(sqldf)

# read past result
cls_res<-c(rep("character",26))
m_res_xls<-read.xls("../HR100_Data_Crawling/data/sl_04_result.xlsx",colClasses=cls_res)

names(m_res_xls)
str(m_res_xls)
m_res_xls$round<-as.numeric(m_res_xls$round)
m_res_xls$length<-as.numeric(m_res_xls$length)
m_res_xls$rank<-as.numeric(m_res_xls$rank)
m_res_xls$id<-as.numeric(m_res_xls$id)
m_res_xls$age<-as.numeric(m_res_xls$age)
m_res_xls$weight<-as.numeric(m_res_xls$weight)
m_res_xls$h_w<-as.numeric(m_res_xls$h_w)
m_res_xls$h_wd<-as.numeric(m_res_xls$h_wd)
m_res_xls$h_rec<-as.numeric(m_res_xls$h_rec)
m_res_xls$S1F_rnk<-as.numeric(m_res_xls$S1F_rnk)
m_res_xls$G1F_rnk<-as.numeric(m_res_xls$G1F_rnk)
m_res_xls$C4_rnk<-as.numeric(m_res_xls$C4_rnk)
m_res_xls$S1F<-as.numeric(m_res_xls$S1F)
m_res_xls$G1F<-as.numeric(m_res_xls$G1F)
m_res_xls$dr_s<-as.numeric(m_res_xls$dr_s)
m_res_xls$dr_st<-as.numeric(m_res_xls$dr_st)
m_res_xls$G3F<-as.numeric(m_res_xls$G3F)
m_res_xls$C4<-as.numeric(m_res_xls$C4)

save(m_res_xls,file="rdt/result.rdata")
head(m_res_xls)
